spiir/aiia-sample

Web/Views/Viia/Accounts.cshtml
https://app.clubhouse.io/spiirdk/story/6995/change-request-data-update-in-viia-sample-web-to-be-a-redirect-instead-of-iframe
=> Redirect on request update instead of showing it in iframe

Web/Controllers/ViiaController.cs
https://app.clubhouse.io/spiirdk/story/9126/don-t-re-sort-transactions-in-sample-app-web
=> Don't re-sort transactions

Web/Controllers/ViiaController.cs, Web/Models/Viia/Account.cs
https://app.clubhouse.io/spiirdk/story/9195/fix-accounts-grouped-by-provider-in-sample-app
=> Update Provider property name

Web/Controllers/ViiaController.cs, Web/Services/ViiaService.cs, Web/Views/Viia/Transactions.cshtml
https://app.clubhouse.io/spiirdk/story/9889/implement-transaction-paging-in-web-sample-app
Not the prettiest thing in the world, but I'm not sure how much can I improve it with server-rendered views.
=> Add infinite pagination for transactions

Web/Controllers/ViiaController.cs, Web/Models/TransactionsViewModel.cs, Web/Models/Viia/Transaction.cs, Web/Services/ViiaService.cs, Web/Views/Viia/Transactions.cshtml
https://app.clubhouse.io/spiirdk/story/10037/add-more-customizability-to-sample-app
=> Add ability to include deleted transactions

Web/ViiaSample.csproj, devops.yaml
https://app.clubhouse.io/spiirdk/story/9177/change-to-use-sentry2
Draft until I update build pipeline
=> Change to use sentry2

Web/Controllers/ViiaController.cs, Web/Models/TransactionQueryRequestViewModel.cs, Web/Models/Viia/ViiaQueryBetweenValuesModel.cs, Web/Models/Viia/ViiaQueryPart.cs, Web/Services/ViiaService.cs, Web/Views/Viia/Transactions.cshtml
https://app.clubhouse.io/spiirdk/story/10438/ui-for-querying-transactions-in-sample-app
=> Add transaction filter UI

Web/Controllers/ViiaController.cs, Web/Models/AccountsViewModel.cs, Web/Models/Viia/BankProvider.cs, Web/Services/ViiaService.cs, Web/Views/Viia/Accounts.cshtml
https://app.clubhouse.io/spiirdk/story/11443/sample-app-preselect-bank
=> Ability to preselct bank provider and bank accounts

Web/Views/Viia/Accounts.cshtml
https://app.clubhouse.io/spiirdk/story/11553/sample-app-error-when-not-choosing-locale-and-click-update-accounts
=> Fix Update account button

Web/Views/Home/Index.cshtml, Web/Views/Shared/_Layout.cshtml, Web/Views/Viia/Accounts.cshtml, Web/wwwroot/css/site.css
https://app.clubhouse.io/spiirdk/story/17658/re-style-the-sample-app
=> restyle sample app iteration II

Web/Views/Viia/GenericViewWithPostMessageOnLoad.cshtml, Web/wwwroot/css/site.css
https://app.clubhouse.io/spiirdk/story/17658/re-style-the-sample-app
=> fix buttons

Web/Views/Viia/Accounts.cshtml, Web/wwwroot/css/site.css
@iagspiir Could you make this new checkbox less ugly? 😅
=> Add a checkbox for select all accounts

Web/Constants/PaymentExecutionTypes.cs, Web/Controllers/ViiaController.cs, Web/Exceptions/UserNotFoundException.cs, Web/Models/CreatePaymentRequestViewModel.cs, Web/Models/CreatePaymentResultViewModel.cs, Web/Models/PaymentsViewModel.cs, Web/Models/Viia/CreatePaymentRequest.cs, Web/Models/Viia/CreatePaymentResponse.cs, Web/Models/Viia/PaymentAmountRequest.cs, Web/Models/Viia/PaymentBBanRequest.cs, Web/Models/Viia/PaymentDestinationRequest.cs, Web/Models/Viia/PaymentRequest.cs, Web/Services/ViiaClientException.cs, Web/Services/ViiaService.cs, Web/Startup.cs, Web/Views/Shared/_Layout.cshtml, Web/Views/Viia/Payments.cshtml, Web/Views/Viia/Transactions.cshtml, Web/ViiaSample.csproj
https://app.clubhouse.io/spiirdk/story/18485/init-payments-from-sample-app
Only for unattended connections atm
=> Initialize payments

Web/Controllers/PaymentController.cs, Web/Models/Viia/InboundPayment.cs, Web/Models/Viia/OutboundPayment.cs, Web/Models/Viia/PaymentIdentifiers.cs, Web/Models/Viia/PaymentReference.cs, Web/Services/ViiaService.cs, Web/Views/Payment/PaymentCallback.cshtml, Web/Views/Payment/PaymentDetails.cshtml
https://app.clubhouse.io/spiirdk/story/19585/update-sample-app-to-refelct-deatils-of-a-payment
=> Show everything in payment status

Web/Controllers/AccountController.cs, Web/Models/AccountsViewModel.cs, Web/Models/Viia/AllAccountSelectedResponse.cs, Web/Services/ViiaService.cs, Web/Views/Account/Accounts.cshtml
https://app.clubhouse.io/spiirdk/story/19653/expose-selectallaccounts-in-sample-app
=> Expose selectAllAccounts

Web/Views/Account/Transactions.cshtml
Prevented sample app from showing transactions if it was null
=> Null check transaction balance

Web/Views/Account/Accounts.cshtml, Web/Views/Home/Index.cshtml, Web/Views/Payment/OutboundPayments.cshtml, Web/Views/Shared/_Layout.cshtml, Web/Views/Viia/GenericViewWithPostMessageOnLoad.cshtml
https://app.clubhouse.io/spiirdk/story/18109/change-name-in-sample-app
=> change name in text for sample app

Web/Models/Viia/Category.cs, Web/Models/Viia/Transaction.cs
Dynamic transaction rendering will automatically show them in transaction page
=> Expose categories

.gitignore, Web/Aiia.Sample.csproj, Web/Controllers/PaymentV2Controller.cs, Web/Models/Aiia/PaymentAuthorization.cs, Web/Models/Aiia/V2/CreatePaymentAuthorizationRequest.cs, Web/Models/Aiia/V2/CreatePaymentAuthorizationResponse.cs, Web/Models/Aiia/V2/CreatePaymentResponseV2.cs, Web/Models/V2/CreatePaymentAuthorizationRequestViewModel.cs, Web/Models/V2/CreatePaymentAuthorizationResultViewModel.cs, Web/Models/V2/CreatePaymentRequestViewModelV2.cs, Web/Models/V2/CreatePaymentResultViewModelV2.cs, Web/Models/V2/PaymentAuthorizationCallbackViewModel.cs, Web/Services/ViiaService.cs, Web/Views/PaymentV2/CreateOutboundPayment.cshtml, Web/Views/PaymentV2/OutboundPayments.cshtml, Web/Views/PaymentV2/PaymentAuthorizationCallback.cshtml, Web/Views/PaymentV2/PaymentAuthorizationDetails.cshtml, Web/Views/PaymentV2/PaymentDetails.cshtml, Web/Views/Shared/_Layout.cshtml, devops.yaml
Models and endpoints for creating payments against Aiia and NAG v2 endpoints and creating an authorization with one or more payments.
Currently works up until the redirect to the Aiia app when creating the payment authorization. The app fails to redirect, as it treats the authorization as a payment and the lookup therefore fails.
https://dev.azure.com/spiir/Delivery/_workitems/edit/3180
=> Support for bulk payments

Web/Controllers/PaymentV2Controller.cs
Revert rename to keep controller in sync with view
=> Fix PaymentV2Controller

Web/Models/Aiia/CreateInboundPaymentRequest.cs, Web/Models/Aiia/InboundPayment.cs, Web/Models/Aiia/PayerToken.cs, Web/Models/CreatePaymentRequestViewModel.cs, Web/Services/ViiaService.cs, Web/Views/Payment/CreateInboundPayment.cshtml, Web/Views/Payment/PaymentDetails.cshtml, Web/appsettings.Development.json, devops.yaml
- Fix appsettings.Development.json - Aiia section was in the wrong place
=> Add payer token support

Web/Startup.cs
Work item:
https://dev.azure.com/spiir/Delivery/_sprints/taskboard/squad-exp-tooling/Delivery/2022/Q4/2022-11?workitem=20670
=> Updated the password requirements to comply with pentester findings

Web/Startup.cs
Work item:
https://dev.azure.com/spiir/Delivery/_sprints/taskboard/squad-exp-tooling/Delivery/2022/Q4/2022-11?workitem=20662
=> Made anti-forgery cookies secure when calling using HTTPS

Web/Startup.cs
=> Revert "Made all http responses come back with a Cache-Control: no-store,no-cache header"

Web/Program.cs
Added .UseIISIntegration() in Program
=> Added .UseIISIntegration() in Program

Web/Startup.cs
=> Made all http responses come back with a Cache-Control: no-store,no-cache header

Web/Program.cs, Web/Startup.cs
Reverts spiir/aiia-sample#169
Kestrel is not supported
=> Revert "Feature/cookie expire time"
